# restart 策略说明：
#   no             ：默认值，容器退出后不会自动重启
#   always         ：无论退出状态如何，容器总是自动重启
#   on-failure     ：仅当容器以非0状态码退出时自动重启，可配合最大重启次数
#   unless-stopped ：容器异常退出或系统重启后会自动重启，除非手动停止

services:
  # redis配置
  redis:
    image: redis:7.2.5
    container_name: study-java-redis-container
    # 优化：添加密码保护，绑定所有IP
    command: redis-server --bind 0.0.0.0 --requirepass ${REDIS_PASSWORD}
    ports:
      - '6381:6379'
    networks:
      - study-java-network
    environment:
      - TZ=${TIMEZONE}
    # 优化：日志轮转，防止磁盘写满
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: on-failure:5 # 遇到异常最多重启5次

  # mysql配置
  mysql:
    image: mysql:8.4.2
    container_name: study-java-mysql-container
    command:
      [
        '--bind-address=0.0.0.0',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--max_allowed_packet=128M',
        '--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
        '--default-time-zone=+8:00',
      ]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: study_java
      TZ: ${TIMEZONE}
    ports:
      - '3308:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - study-java-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p${MYSQL_ROOT_PASSWORD}']
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: on-failure:5 # 遇到异常最多重启5次

  # 后端配置
  springboot:
    image: xcy960815/study-java:${IMAGE_VERSION}
    container_name: study-java-container
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - '12316:8084'
    volumes:
      - ./logs:/study-java/logs
    # 注意：如果遇到日志权限问题，请执行：./fix-logs-permissions.sh
    # 或者手动执行：sudo chown -R 1000:1000 ./logs && chmod -R 755 ./logs
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: ${TIMEZONE}
      # redis配置
      # 使用 Spring Boot 标准环境变量，可以直接覆盖配置文件中的值，无需重新构建镜像
      SPRING_DATA_REDIS_HOST: ${SPRING_REDIS_HOST:-study-java-redis-container}
      SPRING_DATA_REDIS_PORT: ${SPRING_REDIS_PORT:-6379}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      # 兼容旧的环境变量名（如果配置文件使用了自定义变量）
      SPRING_REDIS_HOST: study-java-redis-container
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
      # mysql配置
      SPRING_DATASOURCE_URL: jdbc:mysql://study-java-mysql-container:3306/study_java?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # DeepSeek API配置
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      DEEPSEEK_BASE_URL: ${DEEPSEEK_BASE_URL:-https://api.deepseek.com}
    networks:
      - study-java-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    # 优化：添加健康检查
    # 检查 Java 进程是否存在（ps 命令在基础镜像中通常可用）
    # 如果此方法不可用，可以考虑：
    # 1. 在 Dockerfile 中安装 curl/wget：RUN apt-get update && apt-get install -y curl
    # 2. 添加 Spring Boot Actuator 依赖并配置健康检查端点
    # 3. 暂时移除 depends_on 的 condition，让容器先启动再检查日志
    healthcheck:
      test: ['CMD-SHELL', 'ps aux | grep -q "[s]tudy-java.jar" || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s  # 增加启动等待时间，给应用更多时间启动和连接数据库
    restart: on-failure:5 # 遇到异常最多重启5次

  # 前端配置
  vue:
    image: xcy960815/study-java-web:${WEB_IMAGE_VERSION}
    container_name: study-java-web-container
    #    build: ./frontend  # 假设有前端代码的目录
    ports:
      - '12315:80'
    environment:
      TZ: ${TIMEZONE}
    networks:
      - study-java-network
    depends_on:
      springboot:
        condition: service_healthy
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    restart: on-failure:5 # 遇到异常最多重启5次

volumes:
  mysql-data:
    name: study-java-mysql-data
    # external: true # 保持注释，允许自动创建

networks:
  study-java-network:
    driver: bridge
    name: study-java-network

# 执行指令
# docker-compose -p study-java -f study-java-compose.yml up -d --remove-orphans

# 停止 study-java-web 项目的容器
# docker-compose -p study-java -f study-java-compose.yml down

