


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study-java?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

