server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study-java?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

# 解释部分作为注释：
# 1. jdbc:mysql://localhost:3306/study-java
#    - localhost: 表示本地数据库服务器，端口号为 3306。如果不是本地部署，需更改为实际 IP 地址。
#    - study-java: 表示要连接的 MySQL 数据库名称。
# 2. useUnicode=true
#    - 开启 Unicode 支持，确保 MySQL 正确处理 Unicode 字符。
# 3. serverTimezone=Asia/Shanghai
#    - 设置时区为 Asia/Shanghai，解决时区相关问题。
# 4. characterEncoding=utf8
#    - 设置数据库的字符编码为 UTF-8。
# 5. autoReconnect=true
#    - 允许数据库连接断开后自动重新连接。
# 6. useSSL=false
#    - 关闭 SSL 支持，防止因未配置 SSL 而出现连接问题。
# 7. allowMultiQueries=true
#    - 允许执行多条 SQL 语句。

# 示例 SQL:
# SELECT * FROM users; SELECT * FROM orders;
# 如果 allowMultiQueries 为 false，则不允许执行多条语句。

mybatis:
  mapper-locations: classpath*:mapper/*.xml
